default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: active-prok_development

test:
  <<: *default
  database: active-prok_test

production:
  <<: *default
  database: active-prok
  username: deploy
  password: <%= ENV['ACTIVE-PROK-SERV_DATABASE_PASSWORD'] %>
