# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bdd3e94d95fc396fa560f1fc30d83869b8e18cdde69db1ac50a24699a650e51d3cd83cf3d9439808b92645ccdcf16bf2ff769eeae4a2f3cda28dd7dd26eabf9
  frontend_url: http://localhost:4000

test:
  secret_key_base: 927993261c1c200837d0fa2fc18a1e1a23d9b65bb626c29db13953af79525d1faedcacfb37284383db8bf2a20f8fd45e5dad3ecc6388b2c6e04105060d11479a
  frontend_url: http://localhost:4001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
